#!/usr/bin/env python3
"""
Aggregate one person's results/*.json files into a persistent, readable
profile at profiles/<name>_profile.md — their round history, cumulative
per-category accuracy, and weakest/strongest categories.

Usage:
    python3 scripts/build_profile.py Anna
"""
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "player"


def find_results_for(name: str):
    results_dir = ROOT / "results"
    if not results_dir.exists():
        return []
    slug = slugify(name)
    matches = []
    for path in sorted(results_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        entry_name = data.get("name", "")
        if slugify(entry_name) == slug or slug in path.stem.lower():
            matches.append((path, data))
    return matches


def build(name: str):
    matches = find_results_for(name)
    if not matches:
        print(f"No results/*.json files found for '{name}'.", file=sys.stderr)
        sys.exit(1)

    rounds = []
    category_totals = {}

    for path, data in matches:
        rounds.append(
            {
                "date": data.get("date", "?"),
                "setId": data.get("setId", "?"),
                "score": data.get("score", 0),
                "total": data.get("total", 0),
                "file": path.name,
            }
        )
        for category, stats in data.get("byCategory", {}).items():
            agg = category_totals.setdefault(category, {"correct": 0, "total": 0})
            agg["correct"] += stats.get("correct", 0)
            agg["total"] += stats.get("total", 0)

    rounds.sort(key=lambda r: r["date"])

    category_rows = []
    for category, stats in category_totals.items():
        total = stats["total"]
        pct = round(100 * stats["correct"] / total) if total else 0
        category_rows.append((category, stats["correct"], total, pct))
    category_rows.sort(key=lambda r: r[3])  # weakest first

    display_name = matches[0][1].get("name", name)
    slug = slugify(display_name)

    lines = [
        f"# {display_name} — Quiz Profile",
        "",
        f"_Auto-generated by `scripts/build_profile.py` from {len(matches)} results file(s) — do not hand-edit._",
        f"_Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        "## Rounds played",
        "",
        "| Date | Set | Score |",
        "|---|---|---|",
    ]
    for r in rounds:
        date_str = r["date"][:10] if len(r["date"]) >= 10 else r["date"]
        lines.append(f"| {date_str} | {r['setId']} | {r['score']}/{r['total']} |")

    lines += [
        "",
        "## Cumulative accuracy by category",
        "",
        "| Category | Correct | Total | Accuracy |",
        "|---|---|---|---|",
    ]
    for category, correct, total, pct in category_rows:
        lines.append(f"| {category} | {correct} | {total} | {pct}% |")

    weakest = [c for c in category_rows if c[3] < 70][:3]
    lines += ["", "## Weakest categories (target these next)", ""]
    if weakest:
        for category, correct, total, pct in weakest:
            confidence = " (small sample)" if total < 5 else ""
            lines.append(f"- **{category}** — {pct}% ({correct}/{total}){confidence}")
    else:
        lines.append("- No clear weak spot yet (everything at or above 70% accuracy).")

    out_path = ROOT / "profiles" / f"{slug}_profile.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="Player name to build/update a profile for")
    args = parser.parse_args()
    out_path = build(args.name)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
