#!/usr/bin/env python3
"""
Regenerate questions/asked-log.md: a compact, human-readable ledger of every
question ever asked (across all sets in questions/manifest.json), grouped by
set. Used by the generator agents as a quick duplicate-avoidance reference —
they should still spot-check against the full question JSON, but this file
is what they scan first.

Usage:
    python3 scripts/build_asked_log.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def truncate(text: str, max_words: int = 16) -> str:
    words = text.split()
    if len(words) <= max_words:
        return text
    return " ".join(words[:max_words]) + "…"


def build():
    manifest_path = ROOT / "questions" / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    lines = [
        "# Questions Asked Log",
        "",
        "Auto-generated by `scripts/build_asked_log.py` — do not hand-edit.",
        "Every question's correct-answer subject, grouped by set, so the",
        "generator agents can quickly check what's already been used before",
        "writing new questions.",
        "",
    ]

    total_questions = 0
    for entry in manifest.get("sets", []):
        set_file = ROOT / "questions" / entry["file"]
        if not set_file.exists():
            continue
        questions = json.loads(set_file.read_text(encoding="utf-8"))
        lines.append(f"## {entry.get('label', entry['id'])} (`{entry['file']}`)")
        lines.append("")
        for q in questions:
            answer = q["options"][q["correctIndex"]]["text"]
            snippet = truncate(q["question"])
            lines.append(f"- `{q['id']}` [{q['category']}] — **{answer}** — {snippet}")
            total_questions += 1
        lines.append("")

    lines.append(f"_Total questions logged: {total_questions}_")

    out_path = ROOT / "questions" / "asked-log.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path, total_questions


if __name__ == "__main__":
    path, count = build()
    print(f"Wrote {path} ({count} questions across all sets)")
